apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dags-pvc-claim
  namespace: airflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi