apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: airflow
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/alissonlima/projects/airflow-learning/dags"